Repository Tech-View/TechView-Website, pull requests merged in 2019-11, with the labels that each got.

#17 removing numbring
  docs/miscellaneous.md
  docs/react-basics.md
  docs/react-internationalization.md
  docs/react-native.md
  docs/react-router.md
  docs/react-testing.md
  docs/redux.md
  docs/supported-libs-and-integration.md
Labels: enhancement

#16 Update Logo
  website/siteConfig.js
  website/static/img/favicon.ico
  website/static/img/logo_icon.svg
Labels: help wanted

#21 add missing images with correct folder paths
  website/static/images/devtoolsInspect.png
  website/static/images/devtoolsTab.png
  website/static/images/error_boundary.png
  website/static/images/flux.png
  website/static/images/logo.jpeg
  website/static/images/phases.png
  website/static/images/phases16.3.jpg
  website/static/images/state.jpg
  website/static/images/vdom1.png
  website/static/images/vdom2.png
  website/static/images/vdom3.png
Labels: bug
